### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by redaced** [nodes-php/pubnub#1]
> redaced@DESKTOP-IGK13U2:/mnt/c/Users/redac/Projects/owl$ composer require nodes/pubnub
Using version ^1.0 for nodes/pubnub
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

 > Problem 1
    - nodes/pubnub 1.0.3 requires laravel/framework 5.1.*||5.2.*||5.3.*||5.4.* -> no matching package found.
    - nodes/pubnub 1.0.2 requires laravel/framework 5.1.*||5.2.*||5.3.* -> no matching package found.
    - nodes/pubnub 1.0.1 requires laravel/framework 5.1.*||5.2.*||5.3.* -> no matching package found.
    - nodes/pubnub 1.0.0 requires laravel/framework 5.1.*||5.2.* -> no matching package found.
    - Installation request for nodes/pubnub ^1.0 -> satisfiable by nodes/pubnub[1.0.0, 1.0.1, 1.0.2, 1.0.3].

>Potential causes:
> - A typo in the package name
>- The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

my project running php 7.2, "laravel/framework": "5.6.*".

i need intgration pubnub help me__

**Comment by Casperhr** [comment]
Sorry, we haven't maintained this for a while. Feel free to drop a PR and I will merge it

**Comment by redaced** [comment]
NE==
